AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for HTF AWS Troll Alerting Service - Event Source Adapters

Parameters:
  RedditUserAgent:
    Default: A random string
    Type: String

  RedditClientId:
    Default: zkIgMo74HSHjyw
    Type: String

  RedditClientSecret:
    Default: RBT6Ri7aBa49sLqTOfIuLj50PT79Cg
    Type: String

  RedditRefreshToken:
    Default: 668760736988-znckfSFLYkLbcru_TFLfHStGVgGxeQ
    Type: String

  RedditSubreddit:
    Default: AskReddit
    Type: String

  EventbusArn:
    Description: Name of the Amazon EventBridge bus to which events are published to be processed.
    Default: arn:aws:events:eu-central-1:128894441789:event-bus/htf-het-vaticaan-eventbus
    Type: String

Resources:
  # -----------------------------
  # Functions
  # -----------------------------

  FnSourceAdapterReddit:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../src/fn-sourceAdapterReddit/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 10
      Environment:
        Variables:
          RedditUserAgent: !Sub ${RedditUserAgent}
          RedditClientId: !Sub ${RedditClientId}
          RedditClientSecret: !Sub ${RedditClientSecret}
          RedditRefreshToken: !Sub ${RedditRefreshToken}
          RedditSubreddit: !Sub ${RedditSubreddit}
          EventbusArn: !Sub ${EventbusArn}
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: "rate(1 minute)"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "events:PutEvents"
              Resource:
                - !Sub ${EventbusArn}
            - Effect: Allow
              Action:
                - "ray:PutTraceSegments"
                - "xray:PutTelemetryRecords"
              Resource:
                - "*"
